version: '3'

services:
  web:
    build: .
    ports:
    - 80:80
    container_name: web 
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    
  socket_server:
    #build: .
    image: node:14
    ports:
      - 3000:3000
    container_name: socket_server
    working_dir: /usr/src/app
    command: >
      /bin/sh -c "npm install && node index.js"
    volumes:
      - ./:/usr/src/app
    restart: always


    
