version: '3'

services:
  mqttjs:
    build: .
    ports:
    - 3000:3000
    container_name: socket_server
    volumes:
      - ./:/usr/src/app
    restart: always


  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAIN: '104.236.97.95 -> http://mqttjs:3000'
      STAGE: 'production'
    links:
      - mqttjs
    volumes:
      - https-portal-data:/var/lib/https-portal
volumes:
  https-portal-data: #
      
