version: '3'

services:
  socket_server:
    #build: .
    image: node:14
    ports:
      - 3000:3000
    container_name: socket_server
    working_dir: /usr/src/app
    command: >
      /bin/sh -c "npm install && node index.js"
    volumes:
      - ./:/usr/src/app
    restart: always


  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '8080:80'
      - '443:443'
    environment:
      DOMAIN: 'localhost -> http://socket_server:3000'
      STAGE: 'staging'
    links:
      - socket_server
    volumes:
      - https-portal-data:/var/lib/https-portal
volumes:
  https-portal-data: #
      
